version: '2.2'
services:
  mysql:
    image: mysql:8.0
    container_name: mysql-lottery
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: lottery
      MYSQL_USER: root
      MYSQL_PASSWORD: 123456
    ports:
      - "3307:3306"

